name:  CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:

      - name:  Descarga repositorio
        uses:  actions/checkout@v3

      - name: Build with Gradle Wrapper
        run: ./gradlew build

          
