name:  CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:

      - name:  Descarga repositorio
        uses:  actions/checkout@v3

# Setup java 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

# Setup sonar-scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name:  Run a multiline script
        run:  |
          echo "Hola Mundo"

# Docker

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker
        run: |
          docker build --tag hectorgnux/final-lab-devsecops:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'clagosu/pet-clinic:latest'
          format: 'table'
          #exit-code: 1 PARAMETRO PARA QUIEBRE DE PIPELINE 
      
      - name: Push Docker
        run: | 
          docker push clagosu/pet-clinic
          
