name:  CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:

      - name:  Descarga repositorio
        uses:  actions/checkout@v3

# Setup java 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name:  Run a multiline script
        run:  |
          echo "Hola Mundo"

          
