name:  CI


on:
  push:
    branches: [ release-devsecops ]
  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest

    steps:

      - name:  Punto 1 - Descarga repositorio
        uses:  actions/checkout@v3

      - name: Punto 2 - SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

